Add rectangle draw feature to Sketch on Map sample
Esri/arcgis-runtime-samples-dotnet pull request #1001
Opened 2022-04-05 13:36 UTC by duffh

2022-04-05 16:28 UTC, nCastle1 reviewed
I just noticed this PR is draft after I got halfway through reviewing it.

Please confirm that the approach to button icons works well for WinUI in both light and dark mode.

2022-04-05 16:28 UTC, nCastle1 commented on src/WinUI/ArcGISRuntime.WinUI.Viewer/Samples/GraphicsOverlay/SketchOnMap/SketchOnMap.xaml.cs
> +            //Geometry geometry = _sketchOverlay.SelectedGraphics.FirstOrDefault().Geometry;
Dead code should be removed

2022-04-07 17:36 UTC, ZackAllen requested changes
I recommend adding this sample to the featured samples list.
Also run codemaid on every .cs file in here.

2022-04-07 17:36 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/GraphicsOverlay/SketchOnMap/SketchOnMap.xaml.cs
> +        private async Task DrawButtonClick(SketchCreationMode creationMode)
I recommend renaming this method.
```suggestion
        private async Task StartSketch(SketchCreationMode creationMode)
```

2022-04-07 17:36 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/GraphicsOverlay/SketchOnMap/SketchOnMap.xaml.cs
> +            // Create a map
Comments should end with a period.

2022-04-08 15:47 UTC, asantana917 commented on src/Forms/Shared/Samples/GraphicsOverlay/SketchOnMap/SketchOnMap.xaml.cs
> +            // pass back a new graphic with the appropriate symbol.
This should be capitalize.

2022-04-08 16:04 UTC, ZackAllen approved these changes

2022-04-08 16:06 UTC, asantana917 approved these changes

2022-04-11 15:12 UTC, merged