Create Symbol Styles From Web Styles
Esri/arcgis-runtime-samples-dotnet pull request #1012
Opened 2022-04-18 16:48 UTC by duffh

# Description

Summary of the change and any relevant info.

## Type of change

- [ ] Bug fix
- [x] New sample implementation
- [ ] Sample viewer enhancement
- [ ] Other enhancement

**Platforms tested on**:

- [x] WPF .NET 6
- [ ] WPF Framework
- [x] WinUI
- [x] Xamarin.Forms Android
- [ ] Xamarin.Forms iOS
- [x] Xamarin.Forms UWP

- [ ] UWP
- [ ] Xamarin.Android
- [ ] Xamarin.iOS

## Checklist

- [x] Runs and compiles on all active platforms
- [ ] Legacy platforms still compile and run (if applicable)
- [ ] Branch is up to date with the latest main/v.next
- [ ] All merge conflicts have been resolved
- [ ] Self-review of changes
- [ ] There are no warnings related to changes
- [ ] No unrelated changes have been made to any other code or project files
- [ ] `sample_sync.py` runs without making changes
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [x] Code is commented with correct formatting
- [ ] All variable and method names are good and make sense
- [x] There is no leftover commented code
- [x] Screenshots are correct size and display in description tab

2022-04-19 17:19 UTC, asantana917 requested changes
The sample looks great. I just have one change request but other than that great job.

2022-04-20 04:25 UTC, ZackAllen requested changes
I recommend adding this sample to the featured samples list. The UI for Forms is clean and simple.

2022-04-20 04:25 UTC, ZackAllen commented on src/Forms/Shared/Samples/Symbology/SymbolStylesFromWebStyles/SymbolStylesFromWebStyles.xaml.cs
> +            LegendPopupView.IsVisible = false;
Is this behavior needed? I think the button works fine as is.

2022-04-20 23:10 UTC, asantana917 approved these changes

2022-04-21 16:14 UTC, ZackAllen approved these changes

2022-04-25 15:45 UTC, merged