Add favorite capability to WPF sample viewer
Esri/arcgis-runtime-samples-dotnet pull request #1021
Opened 2022-05-04 11:15 UTC by duffh

# Description

Summary of the change and any relevant info.

## Type of change

- [x] Sample viewer enhancement

**Platforms tested on**:

- [x] WPF .NET 6
- [x] WPF Framework
- [x] WinUI
- [x] Xamarin.Forms Android
- [ ] Xamarin.Forms iOS
- [x] Xamarin.Forms UWP

- [ ] UWP
- [ ] Xamarin.Android
- [ ] Xamarin.iOS

## Checklist

- [x] Runs and compiles on all active platforms
- [x] Branch is up to date with the latest main/v.next
- [x] All merge conflicts have been resolved
- [x] Self-review of changes
- [x] There are no warnings related to changes
- [x] No unrelated changes have been made to any other code or project files
- [x] `sample_sync.py` runs without making changes
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [x] Code is commented with correct formatting
- [x] All variable and method names are good and make sense
- [x] There is no leftover commented code

2022-05-05 17:39 UTC, ZackAllen requested changes

2022-05-05 17:39 UTC, ZackAllen commented on src/ArcGISRuntime.Samples.Shared/Managers/SampleManager.cs
> +#if !(__IOS__ || XAMARIN || WinUI)
We should add tags excluding Android and UWP as well.

2022-05-06 00:10 UTC, nCastle1 reviewed
I think the favorites display could be simplified substantially if the images were replaced by a `Path` (`Path.Data` can be taken from SVG for a star).

2022-05-09 12:57 UTC, duffh commented
>

2022-05-09 15:30 UTC, ZackAllen approved these changes

2022-05-11 16:39 UTC, ZackAllen approved these changes

2022-05-12 10:06 UTC, merged