New sample: Export vector tiles
Esri/arcgis-runtime-samples-dotnet pull request #1048
Opened 2022-06-16 16:29 UTC by duffh

# Description

Implemented new sample to demonstrate how to export tiles from an online vector tile service.

## Type of change

- [ ] Bug fix
- [x] New sample implementation
- [ ] Sample viewer enhancement
- [ ] Other enhancement

**Platforms tested on**:

- [ ] WPF .NET 6
- [x] WPF Framework
- [x] WinUI
- [x] Xamarin.Forms Android
- [ ] Xamarin.Forms iOS
- [x] Xamarin.Forms UWP

## Checklist

- [x] Runs and compiles on all active platforms
- [x] Legacy platforms still compile and run (if applicable)
- [x] Branch is up to date with the latest main/v.next
- [x] All merge conflicts have been resolved
- [x] Self-review of changes
- [x] There are no warnings related to changes
- [x] No unrelated changes have been made to any other code or project files
- [x] `sample_sync.py` runs without making changes
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [x] Code is commented with correct formatting
- [x] All variable and method names are good and make sense
- [x] There is no leftover commented code
- [x] Screenshots are correct size and display in description tab

2022-06-16 18:38 UTC, ZackAllen requested changes
All of the feedback on Export tiles and Export vector tiles for Forms applies to every platform.
The screenshots should show the exported MapView if possible.

2022-06-16 18:38 UTC, ZackAllen commented on src/Forms/Shared/Samples/Layers/ExportVectorTiles/ExportVectorTiles.xaml.cs
> +    [ArcGISRuntime.Samples.Shared.Attributes.OfflineData()]
Delete this line.

2022-06-16 18:38 UTC, ZackAllen commented on src/Forms/Shared/Samples/Layers/ExportVectorTiles/ExportVectorTiles.xaml.cs
> +            _downloadArea.Symbol = simpleLineSymbol;
```suggestion
            _downloadArea.Symbol = new SimpleLineSymbol(SimpleLineSymbolStyle.Solid, System.Drawing.Color.Red, 2);
```

2022-06-16 18:38 UTC, ZackAllen commented on src/Forms/Shared/Samples/Layers/ExportVectorTiles/ExportVectorTiles.xaml.cs
> +                // Hide the cancel job button.
I'd suggest grouping all of these lines with a single comment saying "Update the UI". I think all of the UI stuff is pretty evident from the code and doesn't need individual comments like this.

2022-06-16 18:38 UTC, ZackAllen commented on src/Forms/Shared/Samples/Layers/ExportVectorTiles/ExportVectorTiles.xaml.cs
> +            {
Same comments from the Export Tiles sample apply here.

2022-06-16 22:58 UTC, duffh commented on src/Forms/Shared/Samples/Layers/ExportTiles/ExportTiles.xaml.cs
> +                _job.ProgressChanged += (o, e) =>
Good call.

2022-06-19 21:54 UTC, ZackAllen commented on src/Forms/Shared/Samples/Layers/ExportTiles/ExportTiles.xaml
> +            <ProgressBar x:Name="MyProgressBar"
Could use a `Margin = "5"` so that the progress bar isnt touching the cancel button.

2022-06-19 21:55 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Layers/ExportVectorTiles/ExportVectorTiles.xaml
> +                    <TextBlock x:Name="MyProgressBarLabel"
This UI element still needs a margin it touches the element below.

2022-06-19 21:56 UTC, ZackAllen requested changes
Parts of the UI are still touching due to lack of margins.

2022-06-20 15:23 UTC, merged