Add status check for README.md files
Esri/arcgis-runtime-samples-dotnet pull request #1055
Opened 2022-06-28 11:50 UTC by duffh

## Type of change

- [x] Other enhancement

## Checklist

- [ ] Branch is up to date with the latest main/v.next
- [ ] All merge conflicts have been resolved
- [ ] Self-review of changes
- [ ] There are no warnings related to changes
- [ ] No unrelated changes have been made to any other code or project files
- [ ] All variable and method names are good and make sense
- [ ] There is no leftover commented code

2022-06-30 23:22 UTC, ZackAllen requested changes

2022-06-30 23:22 UTC, ZackAllen commented on tools/CI/README_Metadata_SampleSyncCheck/sample_sync.py
> +import sys
I think we should rename this script to differentiate it from the other script.

2022-06-30 23:22 UTC, ZackAllen commented on tools/CI/README_Metadata_SampleSyncCheck/entry.py
> +    code2 = sp.call(f'python3 /sample_sync.py',  shell=True)
is code2 used?

2022-06-30 23:22 UTC, ZackAllen commented on tools/CI/README_Metadata_SampleSyncCheck/sample_sync.py
> +    subprocess.run(["python", metadata_script_path, "src"])
```suggestion
    subprocess.run(["python", metadata_script_path])
```
IIRC the argument wasn't actually necessary here, something else was the problem at the time.

2022-06-30 23:22 UTC, ZackAllen commented on tools/CI/README_Metadata_StyleCheck/README_style_checker.py
> +  /common-samples/blob/master/tools/net/tag_sorter/tag_sorter.py
References to common-samples shouldnt go in our public repo.

2022-06-30 23:22 UTC, ZackAllen commented on tools/metadata_tools/file_utils.py
> +                print(path_to_file)
Should probably add an informative message to this.
```suggestion
                print("Error reading file: "+path_to_file)
```

2022-06-30 23:22 UTC, ZackAllen commented on tools/metadata_tools/file_utils.py
> +                print(path_to_file)
```suggestion
                print("Error writing file: "+path_to_file)
```

2022-06-30 23:22 UTC, ZackAllen commented on tools/metadata_tools/process_metadata.py
> +from http.client import NETWORK_AUTHENTICATION_REQUIRED
Line can be removed.

2022-06-30 23:22 UTC, ZackAllen commented on tools/metadata_tools/process_metadata.py
> +    readme_text = readme_text[:-1]
```suggestion
    # Remove trailing newline character from readme.
    readme_text = readme_text[:-1]   
```

2022-06-30 23:22 UTC, ZackAllen commented on tools/metadata_tools/process_metadata.py
> +        print(e)
Maybe combine print statements here.

2022-06-30 23:22 UTC, ZackAllen commented on tools/metadata_tools/sample_metadata.py
> +# import requests
We should delete every commented section in this.

2022-06-30 23:25 UTC, ZackAllen commented
Saw this warning from the readme check, any idea how to resolve?
```
[Check README and metadata format for changed files](https://github.com/Esri/arcgis-runtime-samples-dotnet/runs/7135935518?check_suite_focus=true#step:2:7)
Received event from pull_request, but also received a before(87007f750e4e320573a0ee699a55345ca6ec533b) or after(5f6811ad5ff37f13955a974ae6262629c5551f5c) value.
 I am assuming you want to use a Push event but forgot something, so I'm giving you a message.
```

2022-07-01 12:21 UTC, duffh commented
> Saw this warning from the readme check, any idea how to resolve?
> 
> ```
> [Check README and metadata format for changed files](https://github.com/Esri/arcgis-runtime-samples-dotnet/runs/7135935518?check_suite_focus=true#step:2:7)
> Received event from pull_request, but also received a before(87007f750e4e320573a0ee699a55345ca6ec533b) or after(5f6811ad5ff37f13955a974ae6262629c5551f5c) value.
>  I am assuming you want to use a Push event but forgot something, so I'm giving you a message.
> ```

I can see that this warning is referenced in an open issue logged against the GitHub action we are using here. I don't think it's a deal breaker but it is a bit annoying. Looks like the developer has not fixed it in the past 2 years. We could use a different action or accept that this warning message will appear. What do you think?

https://github.com/trilom/file-changes-action/issues/97

2022-07-01 15:37 UTC, ZackAllen commented
> > Saw this warning from the readme check, any idea how to resolve?
> > ```
> > [Check README and metadata format for changed files](https://github.com/Esri/arcgis-runtime-samples-dotnet/runs/7135935518?check_suite_focus=true#step:2:7)
> > Received event from pull_request, but also received a before(87007f750e4e320573a0ee699a55345ca6ec533b) or after(5f6811ad5ff37f13955a974ae6262629c5551f5c) value.
> >  I am assuming you want to use a Push event but forgot something, so I'm giving you a message.
> > ```
> 
> I can see that this warning is referenced in an open issue logged against the GitHub action we are using here. I don't think it's a deal breaker but it is a bit annoying. Looks like the developer has not fixed it in the past 2 years. We could use a different action or accept that this warning message will appear. What do you think?
> 
> [trilom/file-changes-action#97](https://github.com/trilom/file-changes-action/issues/97)

Not a big issue.

2022-07-01 15:41 UTC, ZackAllen commented on tools/CI/README_Metadata_StyleCheck/README_style_checker.py
> +  /common-samples/blob/master/tools/net/tag_sorter/tag_sorter.py
This is not resolved.

2022-07-01 17:11 UTC, ZackAllen approved these changes

2022-07-01 17:12 UTC, merged