New sample: Generate elevation profile with Local Server
Esri/arcgis-runtime-samples-dotnet pull request #1069
Opened 2022-07-29 17:21 UTC by duffh

# Description

Added a new sample to demonstrate how to create an elevation profile using a geoprocessing package executed with ArcGIS Runtime Local Server.

## Type of change

- [x] New sample implementation

**Platforms tested on**:

- [ ] WPF .NET 6
- [x] WPF Framework
- [x] WinUI

## Checklist

- [x] Runs and compiles on all active platforms
- [x] Branch is up to date with the latest main/v.next
- [x] All merge conflicts have been resolved
- [x] Self-review of changes
- [x] There are no warnings related to changes
- [x] No unrelated changes have been made to any other code or project files
- [x] `sample_sync.py` runs without making changes
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [ ] Code is commented with correct formatting
- [ ] All variable and method names are good and make sense
- [x] There is no leftover commented code
- [x] Screenshots are correct size and display in description tab

2022-07-29 23:05 UTC, ZackAllen requested changes

2022-07-29 23:05 UTC, ZackAllen commented on tools/CI/README_Metadata_StyleCheck/README_style_checker.py
> +    'Local Server',
TBD change on this checker script.

2022-07-29 23:05 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml
> +        <Grid.ColumnDefinitions>
All of the Column properties are not needed when using the `BorderStyle`.

2022-07-29 23:05 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml.cs
> +        private Esri.ArcGISRuntime.Geometry.PointCollection _pointCollection;
```suggestion
        private PointCollection _pointCollection;
```

2022-08-01 13:22 UTC, duffh commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml.cs
> +                MyCancelJobButton.Visibility = Visibility.Collapsed;
I prefer the longer form as I think it's more obvious to the user but I'd be happy to swap it over if you think it's unnecessary.

2022-08-01 14:36 UTC, duffh commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml.cs
> +            MapPoint projectedPoint = (MapPoint)GeometryEngine.Project(point, _rasterLayerSpatialReference);
Added a try catch for error output and added a check for a valid `SpatialReference` on click event.

2022-08-01 15:40 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml.cs
> +            await DisplayRaster(_arranRaster);
Awaiting DisplayRaster without a try/catch in our discard would throw an exception that never gets handled properly. I would also move `await DisplayRaster` into the try/catch.

2022-08-01 15:44 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml.cs
> +            MapPoint cameraPositionPoint = new MapPoint(centerX + lengthY * 2, centerY - lengthX * 2, 1200,
```suggestion
            var cameraPositionPoint = new MapPoint(centerX + lengthY * 2, centerY - lengthX * 2, 1200,
```
IN our style we can use `var` when it precedes a constructor.

2022-08-01 16:59 UTC, ZackAllen approved these changes

2022-08-02 09:53 UTC, merged