MAUI: Improve Sample Styling on Android
Esri/arcgis-runtime-samples-dotnet pull request #1136
Opened 2022-11-09 01:45 UTC by amweis226

# Description

Change app theme colors to account for dark theme and fix entry color on Android

## Type of change

- [ ] Bug fix
- [ ] New sample implementation
- [x] Sample viewer enhancement
- [ ] Other enhancement

**Platforms tested on**:

- [x] MAUI

## Checklist

- [x] Runs and compiles on all active platforms
- [x] Legacy platforms still compile and run (if applicable)
- [x] Branch is up to date with the latest main/v.next
- [x] All merge conflicts have been resolved
- [x] Self-review of changes
- [x] There are no warnings related to changes
- [x] No unrelated changes have been made to any other code or project files
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [x] There is no leftover commented code

2022-11-09 22:30 UTC, ZackAllen requested changes
![No track lines](https://user-images.githubusercontent.com/16495151/200955909-a87f3ce3-6684-49f8-bd4e-a8a6e1ee75fc.jpg)

Track lines dont show by default in Android Light mode.
The button styles are better than before but I still think we should change them to feature text colors that match labels.

2022-11-10 18:30 UTC, ZackAllen approved these changes

2022-11-11 00:52 UTC, pMaske approved these changes
Looks good @amweis226 :-)

2022-11-11 01:05 UTC, amweis226 commented on src/MAUI/Maui.Samples/Resources/Styles/Styles.xaml
> +                            <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource LightGray}, Dark={StaticResource DarkGray}}" />
Noting that we resolved this together over a video meeting

2022-11-11 01:05 UTC, amweis226 commented on src/MAUI/Maui.Samples/Resources/Styles/Styles.xaml
> +        <Setter Property="MinimumTrackColor" Value="{OnPlatform Default={AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}, Android={AppThemeBinding Light={StaticResource P
Noting that we resolved this together over a video meeting

2022-11-11 01:06 UTC, merged