Rebrand samples to `ArcGIS Maps SDK for .NET`
Esri/arcgis-runtime-samples-dotnet pull request #1145
Opened 2022-11-17 00:42 UTC by ZackAllen

# Description

This PR updates all of our sample names to reflect the rebranding to ArcGIS Maps SDK for .NET.
[This blogpost](https://esriurl.com/maps-sdks-announcement) explains the upcoming change.

In draft for now, still trying to iron out some details.

## Type of change

- [ ] Other enhancement

**Platforms tested on**:

- [ ] WPF .NET 6
- [ ] WPF Framework
- [ ] WinUI
- [ ] Maui Android
- [ ] Maui iOS
- [ ] Maui MacCatalyst
- [ ] Maui WinUI
- [ ] UWP

## Checklist

- [ ] Runs and compiles on all active platforms
- [ ] Legacy platforms still compile and run (if applicable)
- [ ] Branch is up to date with the latest main/v.next
- [ ] All merge conflicts have been resolved
- [ ] Self-review of changes
- [ ] There are no warnings related to changes
- [ ] No unrelated changes have been made to any other code or project files
- [ ] `sample_sync.py` runs without making changes
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] Code is commented with correct formatting
- [ ] All variable and method names are good and make sense
- [ ] There is no leftover commented code
- [ ] Screenshots are correct size and display in description tab

2022-12-02 20:50 UTC, nCastle1 approved these changes

2022-12-05 19:11 UTC, amweis226 approved these changes

2022-12-05 19:15 UTC, pMaske requested changes
@ZackAllen thanks for updating this.
I have few comments and suggestions but may have missed to comment on all instances because PR is too big
Please see the comments and apply them to places wherever applicable.

2022-12-05 19:15 UTC, pMaske commented on src/MAUI/Maui.Samples/Samples/Layers/RasterLayerRasterFunction/RasterLayerRasterFunction.xaml.cs
> +                // NOTE: The sample zooms to the extent of the ImageServiceRaster. Currently the ArcGIS Maps SDK for .NET does not
If this general statement across all SDKs then we should say ArcGIS Maps SDK for Native Apps

2022-12-05 19:15 UTC, pMaske commented on src/MAUI/Maui.Samples/Samples/Search/FindAddress/FindAddress.xaml.cs
> +                "ArcGISMapsSDK.Resources.PictureMarkerSymbols.pin_star_blue.png");
We should avoid using `ArcGISMapsSDK` here. Perhaps need to think of a better name.

2022-12-05 19:15 UTC, pMaske commented on src/MAUI/Maui.Samples/Helpers/ArcGISLoginPrompt.cs
> +        // - The Client ID for an app registered with the server (the ID below is for a public app created by the ArcGIS Maps SDK team).
```suggestion
        // - The Client ID for an app registered with the server (the ID below is for a public app created by the ArcGIS Maps SDK  for Native Apps team).
```

2022-12-05 19:15 UTC, pMaske commented on src/MAUI/Maui.Samples/Resources/SettingsPage/about.md
> +# ArcGIS Maps SDK Samples (MAUI)
```suggestion
# ArcGIS Maps SDK Samples for .NET (.NET MAUI)
```

2022-12-06 19:41 UTC, merged