Updates to OAuth samples
Esri/arcgis-runtime-samples-dotnet pull request #904
Opened 2021-06-30 01:45 UTC by ZackAllen

This PR aims to fix several issues with OAuth in the samples.
- Offline map samples use an OAuth pattern where API key is sufficient.
- Create and save map, Search for webmap, Authenticate with OAuth, and Navigate in AR all use repeat OAuth code. It is better if each platform has its own helper class for authentication.
- Authentication itself is using the wrong `TokenAuthenticationType` in some cases.
- There are several bugs in OAuth samples (especially when a login is cancelled).

2021-07-20 00:31 UTC, mbranscomb requested changes
@ZackAllen Wow, this is a massive PR - overall nice work.

- Requested/suggested a few changes.
- Nice to see async voids being gradually replaced with async tasks where appropriate. I noticed though that not all are updated in this PR, which is OK, as long as there's a plan to address the others in the future.

2021-07-20 00:31 UTC, mbranscomb commented on src/Forms/iOS/ArcGISRuntime.Xamarin.Forms.iOS.csproj
> +    <CodesignKey>Apple Development: Zack Allen (H3TP7QX4B5)</CodesignKey>
Is this intentional?

2021-07-20 00:31 UTC, mbranscomb commented on src/Forms/iOS/ArcGISRuntime.Xamarin.Forms.iOS.csproj
> +    <CodesignKey>Apple Distribution: ESRI (75Z67E6SV2)</CodesignKey>
Probably remove this?

2021-07-20 00:31 UTC, mbranscomb commented on src/Forms/iOS/ArcGISRuntime.Xamarin.Forms.iOS.csproj
> +    <CodesignProvision>com.esri.* Wildcard Distribution</CodesignProvision>
Intentional?

2021-07-20 00:31 UTC, mbranscomb commented on src/UWP/ArcGISRuntime.UWP.Viewer/Helpers/ArcGISLoginPrompt.cs
> +            AuthenticationManager thisAuthenticationManager = AuthenticationManager.Current;
I'd remove this in favor of using `AuthenticationManager.Current` directly below.

2021-07-20 00:31 UTC, mbranscomb commented on src/UWP/ArcGISRuntime.UWP.Viewer/Helpers/ArcGISLoginPrompt.cs
> +            thisAuthenticationManager.RegisterServer(portalServerInfo);
Use `AuthenticationManager.Current`?

2021-07-20 00:31 UTC, mbranscomb commented on src/UWP/ArcGISRuntime.UWP.Viewer/Helpers/ArcGISLoginPrompt.cs
> +            thisAuthenticationManager.ChallengeHandler = new ChallengeHandler(PromptCredentialAsync);
Use `AuthenticationManager.Current`?

2021-07-20 00:31 UTC, mbranscomb commented on src/UWP/ArcGISRuntime.UWP.Viewer/Samples/Map/AuthorMap/AuthorMap.xaml.cs
> +                _ = MyMapView.Map.Basemap.LoadAsync();
Is loading the basemap specifically the same pattern used in the AuthorMap samples on the other .NET platforms?

2021-07-20 00:31 UTC, mbranscomb commented on src/WPF/ArcGISRuntime.WPF.Viewer/Helpers/ArcGISLoginPrompt.cs
> +                    // Use the OAuth implicit grant flow
OAuthAuthorizationCode

2021-07-20 00:31 UTC, mbranscomb commented on src/WPF/ArcGISRuntime.WPF.Viewer/Helpers/ArcGISLoginPrompt.cs
> +                // Use OAuthClientCredentials if you need a refresh token (and have specified a valid client secret).
```suggestion
                // Use OAuthClientCredentials if you have specified a client secret.
```

2021-07-20 00:31 UTC, mbranscomb commented on src/WPF/ArcGISRuntime.WPF.Viewer/Helpers/ArcGISLoginPrompt.cs
> +            AuthenticationManager thisAuthenticationManager = AuthenticationManager.Current;
Use `AuthenticationManager.Current` directly below.

2021-07-20 00:31 UTC, mbranscomb commented on src/WPF/ArcGISRuntime.WPF.Viewer/Helpers/ArcGISLoginPrompt.cs
> +            thisAuthenticationManager.RegisterServer(portalServerInfo);
Use `AuthenticationManager.Current` directly

2021-07-20 00:31 UTC, mbranscomb commented on src/WPF/ArcGISRuntime.WPF.Viewer/Helpers/ArcGISLoginPrompt.cs
> +            thisAuthenticationManager.OAuthAuthorizeHandler = new OAuthAuthorize();
Use `AuthenticationManager.Current` directly

2021-07-20 00:31 UTC, mbranscomb commented on src/WPF/ArcGISRuntime.WPF.Viewer/Helpers/ArcGISLoginPrompt.cs
> +            thisAuthenticationManager.ChallengeHandler = new ChallengeHandler(PromptCredentialAsync);
Use `AuthenticationManager.Current` directly

2021-07-20 00:31 UTC, mbranscomb commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Map/AuthorMap/AuthorMap.xaml.cs
> +                _ = MyMapView.Map.Basemap.LoadAsync();
Await the LoadAsync.

2021-07-20 00:31 UTC, mbranscomb commented on src/iOS/Xamarin.iOS/Helpers/ArcGISLoginPrompt.cs
> +                //await Application.Current.MainPage.DisplayAlert("Login failed", ex.Message, "OK");
Is this intentionally commented out?

2021-07-20 00:31 UTC, mbranscomb commented on src/iOS/Xamarin.iOS/Helpers/ArcGISLoginPrompt.cs
> +                // Use OAuthClientCredentials if you need a refresh token (and have specified a valid client secret).
```suggestion
                // Use OAuthClientCredentials if you have specified a client secret.
```

2021-07-20 00:31 UTC, mbranscomb commented on src/iOS/Xamarin.iOS/Samples/Map/AuthorMap/AuthorMap.cs
> +                _ = _myMapView.Map.Basemap.LoadAsync();
Await the LoadAsync

What happens if it returns an exception?

2021-07-20 17:13 UTC, ZackAllen commented on src/Android/Xamarin.Android/Samples/Map/SearchPortalMaps/SearchPortalMaps.cs
> +            bool loggedIn = await ArcGISLoginPrompt.EnsureAGOLCredentialAsync(this);
`EnsureAGOLCredentialAsync` catches all potential exceptions. Will always return a bool.

2021-07-20 17:32 UTC, ZackAllen commented
The author map basemap loads were an artifact from when I was trying to rewrite the sample by setting the API key on the basemap. They are not needed for the new pattern.

2021-07-21 21:17 UTC, cgutierrez-gis commented
Some issues I'm seeing in the impacted samples:

(all sample viewers)
Create and save map - Selecting to create a new map wipes out map view and does not repopulate the map view after a selection is made.

2021-07-29 20:30 UTC, nCastle1 requested changes
I noticed on WPF that when switching to a sample with OAuth, the OAuth dialog is shown before the new sample's UI is shown. Ideally the old sample would be hidden and replaced by the new sample, or at least replaced with a loading screen, before the OAuth dialog appears.

The iOS samples have a lot of unused `OAuth2Authenticator` member variables, I'd like to see those cleaned up.

Everything else looks good.

2021-08-03 00:33 UTC, nCastle1 approved these changes

2021-08-04 17:59 UTC, mbranscomb approved these changes

2021-08-04 18:00 UTC, mbranscomb commented
@ZackAllen Looks like you resolved all my comments/questions. 

A good and necessary enhancement. 

Approved.

2021-08-04 18:41 UTC, merged