Add BasemapGallery toolkit component sample.
Esri/arcgis-runtime-samples-dotnet pull request #982
Opened 2022-03-10 00:14 UTC by asantana917

2022-03-14 18:15 UTC, nCastle1 requested changes
Sample looks good, I'm glad to see the BasemapGallery toolkit component being used here.

Feedback:

- metadata.json should reference the Toolkit package
- You don't need to use the BasemapSelected event. It would be better to bind the `BasemapGallery` to the `MapView`'s map via the `GeoModel` bindable property. (readme will need to be updated)
- The BasemapGallery does not require a Portal to be set, it will use ArcGIS Online by default. Once the binding is set up and a map is added to the MapView, there will be no need for the Initialize and BasemapSelected methods.

2022-03-14 21:41 UTC, ZackAllen requested changes

2022-03-14 21:41 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Map/ChangeBasemap/readme.md
> +* BasemapGallery
We should add tags for toolkit and gallery.

2022-03-14 21:41 UTC, ZackAllen commented on src/Forms/Shared/Samples/Map/ChangeBasemap/ChangeBasemap.xaml
> +    <Grid>
The behavior of the UI isn't super intuitive.
Maybe hide the basemap options after a selection is made?
Or change the button text when the gallery is displayed (i.e. flip between "Show basemaps" and "Hide basemaps".

2022-03-14 21:41 UTC, ZackAllen commented on src/Forms/Shared/Samples/Map/ChangeBasemap/ChangeBasemap.xaml
> +        <toolkit:BasemapGallery x:Name="MyBasemapGallery" BasemapSelected="BasemapSelected" />
The transparent background can make the text hard to read. I would add an opaque background here.

2022-03-14 21:41 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Map/ChangeBasemap/ChangeBasemap.xaml.cs
>              Initialize();
```suggestion
            _ = Initialize();
```
Needed for the warning.

2022-03-18 21:10 UTC, nCastle1 requested changes
Looking good, just one last issue to fix.

2022-03-18 21:10 UTC, nCastle1 commented on src/Forms/Shared/Samples/Map/ChangeBasemap/ChangeBasemap.xaml
> +                                Opacity="0.85" />
Opacity shouldn't be set this way. It ends up being inherited by subcomponents of the view, which leads to unexpected behavior with the templates. I think the UI is clear enough with the toggle button.

2022-03-18 21:23 UTC, nCastle1 approved these changes

2022-03-21 16:47 UTC, ZackAllen approved these changes

2022-03-21 16:49 UTC, merged