Combine feature request mode samples
Esri/arcgis-runtime-samples-dotnet pull request #998
Opened 2022-04-01 23:02 UTC by asantana917

2022-04-05 21:01 UTC, nCastle1 requested changes
Sample looks great, I really like this simplification.

Only a few comments on how the doc/comments can be clarified, and some minor suggestions for improving code clarity.

I did see some changes to the viewer framework that I would like to see reverted/removed before approval.

2022-04-05 22:24 UTC, asantana917 commented on src/Forms/Shared/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +                WhereClause = "Condition < '4'",
I was following the format of other platforms but we can omit the `WhereClause` to show consistency across the different request modes.

2022-04-06 20:53 UTC, ZackAllen requested changes
We discussed the radio button / populate button change today.
I suggest adding this sample to the featured samples list.

2022-04-06 20:53 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +                MessageBox.Show(ex.ToString(), "Error");
```suggestion
                MessageBox.Show(ex.Message, ex.GetType().Name, MessageBoxButton.OK, MessageBoxImage.Error);
```
`ex.ToString()` doesnt give very good information. I recommend using ex.message in the error messages for this implementation.

2022-04-06 20:53 UTC, ZackAllen commented on src/WinUI/ArcGISRuntime.WinUI.Viewer/Samples/Data/ToggleBetweenFeatureRequestModes/readme.metadata.json
> +    "keywords": ["cache",
This metadata is out of sync. If you run the updated version of the script from the latest v.next it will resolve this.

2022-04-06 20:53 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/ArcGISRuntime.WPF.Viewer.NetFramework.csproj
>    </ItemGroup>
There are several issues with this file, I will open a separate PR to update it.

2022-04-08 22:15 UTC, ZackAllen commented on src/Forms/Shared/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +                    if (PopulateMap.IsEnabled == true)
If checks are not necessary here, you can just set enabled.

2022-04-08 22:15 UTC, ZackAllen commented on src/Forms/Shared/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +        private async void PopulateButtonClick(object sender, EventArgs e)
We should separate this into its own task method so we can avoid `async void`.

2022-04-08 22:15 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +            if (PopulateMap.IsEnabled == true)
No if needed here.

2022-04-11 16:12 UTC, duffh commented
Looks good, I have left a couple of minor comments. Please run the xaml formatter on each of the xaml files as some of the properties are in an inconsistent order.

2022-04-11 16:12 UTC, duffh commented on src/Forms/Shared/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml
> +             xmlns:mapping="clr-namespace:Esri.ArcGISRuntime.Mapping;assembly=Esri.ArcGISRuntime">
This line is not referenced and can be removed.

2022-04-11 16:12 UTC, duffh commented on src/WinUI/ArcGISRuntime.WinUI.Viewer/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml
> +             xmlns:esri="using:Esri.ArcGISRuntime"
This line is not referenced and can be removed.

2022-04-12 15:41 UTC, ZackAllen commented on src/Forms/Shared/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +        private async void FetchCacheManually()
This should be async Task

2022-04-12 15:41 UTC, ZackAllen commented on src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +        private async void FetchCacheManually()
Should be async Task

2022-04-12 15:41 UTC, ZackAllen commented on src/WinUI/ArcGISRuntime.WinUI.Viewer/Samples/Data/ToggleBetweenFeatureRequestModes/ToggleBetweenFeatureRequestModes.xaml.cs
> +        {
Should be async task

2022-04-12 18:00 UTC, ZackAllen approved these changes

2022-04-12 18:34 UTC, merged